### PR TITLE
Return default value None if attribute choices doesn't exist

### PR DESCRIPTION
**Pull request by viktor2097**
Related to #273 and #293 

Very minimal change that should have no impact on the code other than making sure iterated fields have a .choices attribute.

### CODE REVIEW

**Comment by haard** [comment]
What is blocking this PR? I can't see test results, but the tests pass locally for me on this branch.

**Comment by haard** [comment]
Ping @ndwhelan / @viktor2097 - any chance to get this merged (assuming CI passes)?

**Comment by haard** [comment]
@Linkid @hramezani - any chance of progressing this one?

**Comment by hramezani** [comment]
@viktor2097 Could you please add a regression test?

**Comment by hramezani** [comment]
@haard Do you still have this problem with the new `django-auditlog` release? If so, please provide me a small example to reproduce the problem.
Thanks.

**Comment by haard** [comment]
We still have the same issue 
```
auditlog/models.py", line 306, in changes_display_dict
    if getattr(field, "choices") and len(field.choices) > 0:
AttributeError: 'ManyToOneRel' object has no attribute 'choices'
```
I'll try to create a minimal example triggering it.

**Comment by hramezani** [comment]
Superseded by https://github.com/jazzband/django-auditlog/pull/390

**Pull request closed without merging**
