### PR TITLE
Using changes_dict in admin list

### LINKED ISSUE #477: TypeError object of type 'NoneType' has no len() when changes are empty
The admin logentry list throws a `TypeError object of type 'NoneType' has no len()` when json.loads() return None
I think this comes from https://github.com/jazzband/django-auditlog/blob/703e3e4ba6ba7127cbd6a1bbf2597504089ba78c/auditlog/mixins.py#L58
where:
```python
changes = json.loads(obj.changes)
s = "" if len(changes) == 1 else "s"
        fields = ", ".join(changes.keys())
```

this is related (if not the exact same thing) to #471 

I think a fix would be as simple as replacing `json.loads()` by `obj.changes_dict`

### PR DESCRIPTION
**Pull request by rptmat57**
Using changes_dict to fix potential TypeError when changes are None in admin
Fixes #477

### CODE REVIEW

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
Thanks @rptmat57 :+1:

**Comment by rptmat57** [comment]
I noticed even though this accepted and closed a month and a half ago, it wasn't included in the latest release.
In fact the last release only had a small bug fix. Is that because of the upcoming major 3.0.0 release?

**Comment by hramezani** [comment]
@rptmat57 Yes exactly. we are preparing `v3` which is a major release

**Comment by rptmat57** [comment]
ok thanks for responding so quickly! appreciate it

**Pull request merged**
