### PR TITLE
Moving middleware user auth check to `set_actor()`

### PR DESCRIPTION
**Pull request by ndwhelan**
Move the check for whether the user is authenticated from before
registering `set_actor()` as the `pre_save` signal receiver
in to `set_actor()`. This enables two things:

1. `remote_addr` in the `LogEntry` is set even if the user is
   not authenticated.
2. This middleware no longer execute before the user is set
   on the request. Some frameworks may set this in a
   following middleware. Some frameworks, such as the widely
   adopeted Django Rest Framework do not set this as part
   of a middleware. So, the upshot of hit is that the
   actor will not be set when using Django Rest Framework.

### CODE REVIEW

**Comment by ndwhelan** [comment]
Addresses #277

**Comment by ndwhelan** [comment]
This is probably solved by PR #262

**Comment by alieh-rymasheuski** [comment]
This is actually not solved in #262. #262 sets both actor and remote_addr only for authenticated users, which is exactly the issue attempted to be resolved by this pull request.

**Comment by aqeelat** [comment]
Superseded by #484
@hramezani

**Comment by hramezani** [comment]
Thanks @ndwhelan for the initial patch and @aqeelat for continuing on this.

**Pull request closed without merging**
