### PR TITLE
Add content type to resource field

### PR DESCRIPTION
**Pull request by smoeinbbp**
This will add content type name to resource_url field.

### CODE REVIEW

**Comment by smoeinbbp** [comment]
Hi @jjkester, can you look on this one?

**Comment by Linkid** [comment]
Hi! Could you rebase your PR, please ? Thank you.

**Comment by smoeinbbp** [comment]
Hi @Linkid,
Done.

**Comment by Linkid** [comment]
QA is not passing. It should be quick to fix ;)

**Review by Linkid — APPROVED** [review]

**Comment by Linkid** [comment]
Thank you :).

**Pull request merged**
