### PR TITLE
Add locale

### PR DESCRIPTION
**Pull request by lsaavedr**
Added locale to translate app in admin. Also I'm added two additional files:

 - manage.py
 - app.py

`app.py` is needed only to translate the app-name, in the other hand `manage.py` is added to generate translation .po file in other language with django tools, for example with:
```console
$ python manage.py makemessages --locale fr
```
it is generates .po french file translation,

regards,
Luis

### CODE REVIEW

**Comment by lsaavedr** [comment]
fails due python3.5 support having been removed from setuptools-scm:

https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v600

**Review by Linkid — CHANGES_REQUESTED** [review]
Hi! Thanks for this PR, it's really cool !

I think the `manage.py` file is not necessary thanks to the `django-admin` command: `django-admin makemessages --locale=fr`. Maybe this command could be added to the doc.

**Comment by lsaavedr** [comment]
rebase master and remove manage.py

**Comment by hramezani** [comment]
Hi @lsaavedr,
Thanks for your PR :+1: 

Could you please refresh the PR and add a change log entry?

**Comment by hramezani** [comment]
Closing due to inactivity. Feel free to open it when you have time to work on this again.

**Pull request closed without merging**
