### PR TITLE
Support search by custom USERNAME_FIELD

### LINKED ISSUE #431: Related Field got invalid lookup: username
- noticed while deleting logentires

### PR DESCRIPTION
**Pull request by alieh-rymasheuski**
Fixes #431

### CODE REVIEW

**Comment by hramezani** [comment]
Thanks @alieh-rymasheuski for the quick fix.
Is it possible to add a test for this? Also change log is missing.

I think we can prepare `2.2` when we merge this.

**Comment by alieh-rymasheuski** [comment]
@hramezani, the admin configuration is a tricky thing to test, especially given that we evaluate `LogEntryAdmin.search_fields` on import (so we are limited in our options of using `unittest.mock.patch` to tinker with the user model). If you have an idea how to test this properly without switching the user model for all tests to a non-default one, please try to write such test. Otherwise let's keep this change untested (together with the majority of the configuration of the admin).

**Comment by hramezani** [comment]
> @hramezani, the admin configuration is a tricky thing to test, especially given that we evaluate `LogEntryAdmin.search_fields` on import (so we are limited in our options of using `unittest.mock.patch` to tinker with the user model). If you have an idea how to test this properly without switching the user model for all tests to a non-default one, please try to write such test. Otherwise let's keep this change untested (together with the majority of the configuration of the admin).
> 
> Added the change log - sorry for not doing it before.

@alieh-rymasheuski agree.

Question: Have you tested it locally?

@dev-fairshares Could you please confirm the fix?

**Comment by alieh-rymasheuski** [comment]
@hramezani, I tested and double-tested this change, it works for me.

**Review by hramezani — APPROVED** [review]

**Comment by hramezani** [comment]
Thanks @alieh-rymasheuski fix fixing and @dev-fairshares for checking :+1:

**Pull request merged**
