### PR TITLE
Accept dateutil versions greater than 2.6.0

### PR DESCRIPTION
**Pull request by ogu2**
This will stop unnecessarily pinning version and make it more compatible with other libraries

### CODE REVIEW

**Comment by dalys** [comment]
It would be great to have this merged. I want to use django-auditlog but right now it's incompatible with other packages because of this.

**Comment by dalys** [comment]
@jjkester It seems you need to approve this PR for this to be able to merge. Would you mind taking a look? Thanks a lot!

**Comment by ebertti** [comment]
Hi, can merge this. Please :) 

I'm having conflicts with another pacakges becouse of this.

```
ERROR: ERROR: Could not find a version that matches python-dateutil<2.7.0,==2.6.0,>=2.6.1
Tried: 1.4, 1.4.1, 1.5, 2.1, 2.2, 2.3, 2.3, 2.4.0, 2.4.0, 2.4.1, 2.4.1, 2.4.1.post1, 2.4.1.post1, 2.4.2, 2.4.2, 2.
5.0, 2.5.0, 2.5.0, 2.5.1, 2.5.1, 2.5.1, 2.5.2, 2.5.2, 2.5.2, 2.5.3, 2.5.3, 2.5.3, 2.6.0, 2.6.0, 2.6.0, 2.6.1, 2.6.
1, 2.7.0, 2.7.0, 2.7.1, 2.7.1, 2.7.2, 2.7.2, 2.7.3, 2.7.3, 2.7.4, 2.7.4, 2.7.5, 2.7.5, 2.8.0, 2.8.0
There are incompatible versions in the resolved dependencies.

```

**Comment by Sharaf-Ansari** [comment]
Would be awesome if this could be merged soon. Facing conflicting dependencies because of this

**Comment by sergray** [comment]
It might be good to limit the upper version of `python-dateutil` with `<3`

**Comment by hckjck** [comment]
Hey guys, this is super annoying and open for more then a year now. It does not look like that complicated... could you please finally merge this? Thanks!

**Comment by Linkid** [comment]
Arg, already done in https://github.com/jazzband/django-auditlog/commit/33fa2490714954b189e24963e4586f86ce4f99c2. Thank you anyway.

**Pull request closed without merging**
