### PR TITLE
Prepare release 3.0.0-beta.3

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Review by peymanslh — APPROVED** [review]

**Comment by jgillard** [comment]
This isn't on PyPi atm

**Comment by hramezani** [comment]
> This isn't on PyPi atm

Not yet, we have problem in building 
https://github.com/jazzband/django-auditlog/actions/runs/6860523927/job/18654499858

**Comment by hramezani** [comment]
@jgillard it has been released!

**Comment by jgillard** [comment]
Thank you 🙌

**Pull request merged**
