### PR TITLE
Add a DB index to `LogEntry`'s `action` field

### PR DESCRIPTION
**Pull request by crazyscientist**
For some applications the possibility to filter by the `action` field might be really interesting. However the lack of an index can lead to severe reduction of such queries.

The simplest solution: Let's a DB index on that field :)

### CODE REVIEW

**Comment by crazyscientist** [comment]
Hello, this is really almost a trivial pull request.

Maybe, after 10 months, somebody would like to take the time to review this?

**Comment by crazyscientist** [comment]
> Hello, this is really almost a trivial pull request.
> 
> Maybe, after 10 months, somebody would like to take the time to review this?

@jjkester or someone else?

**Comment by crazyscientist** [comment]
@jezdez Sorry to bother you as well. Can I interest you in reviewing this pull request?

**Review by Linkid — APPROVED** [review]

**Comment by Linkid** [comment]
Hi! Thanks for this PR.

**Pull request merged**
