### PR TITLE
tests:  Check cases when reverse related field DoesNotExist.

### PR DESCRIPTION
**Pull request by rrauenza**
See https://github.com/jjkester/django-auditlog/issues/17

### CODE REVIEW

**Comment by jjkester** [comment]
Thanks for the fix, I restarted the Travis CI job. Let's see if everything is green.

**Comment by jjkester** [comment]
Can you rebase on `master`?

**Comment by rrauenza** [comment]
Sorry --just saw this recently.  Rebased and repushed.

**Comment by rrauenza** [comment]
@hramezani Ok, looks ready to go!

**Comment by hramezani** [comment]
Thanks @rrauenza for refreshing the patch.
If I apply your changes on `auditlog_tests/models.py` locally and then run the test, they will pass successfully.
You need to add a proper regression test for this patch.
Also, please add an entry to [changelog](https://github.com/jazzband/django-auditlog/blob/master/CHANGELOG.md).

**Comment by hramezani** [comment]
@rrauenza Could you please create a small project with the problem and send it to me (`hasan.r67@gmail.com`)? Then I will take a look and try to add a proper test for the patch.

Or even a model with a fixture that reproduces the problem helps as well.

Thanks!

**Comment by rrauenza** [comment]
I submitted this 2 years ago, so this isn't even something I'm actively working on anymore and I'm no longer using this package.  Through a discussion with @jjkester at the time in one of the linked issues, he was trying to improve some related model stuff.  So I submitted a patch.

The code I've changed shows what the problem is -- that related field metadata doesn't have the `default ` attribute to lookup.  So we need to handle that case by checking if the field exists.

If you can find a way to trigger that code with a model than has a OneToOne related field in it, then it should reproduce.  For me, I think it was when I was importing fixtures.

**Comment by rrauenza** [comment]
Hmm... this is in the diff code, even though I was having trouble with fixtures.  So maybe it can be reproduced simply in the diff tests... checking.

**Comment by rrauenza** [comment]
@hramezani I'm not sure what those errors are... they kind of look unrelated?

**Comment by hramezani** [comment]
@rrauenza Thanks for your information. but this error is still not reproducible for me. it means if we add your changes in [auditlog_tests/models.py](https://github.com/jazzband/django-auditlog/pull/252/files#diff-4f8b9df1dbfff67d8ddf0926cbc63c9da009e6cecfa6f373e1cd5dc4ac9cb698) and [auditlog_tests/tests.py](https://github.com/jazzband/django-auditlog/pull/252/files#diff-eb9581b1c35dba2bdbfcf71d8c389814416cdbe08a5dadadc0ce3ab4520b61b2) to the master and run the test it will be passed successfully.

> @hramezani I'm not sure what those errors are in the ci... they kind of look unrelated?

The CI failure is related to the minimum Postgres required by Django main that is updated to Postgres 12. it is already fixed in https://github.com/jazzband/django-auditlog/commit/d5d65cae2af8025b433665d3091c0b1745bc44d5. You just need to rebase your branch

**Comment by rrauenza** [comment]
...it seems my test didn't get pushed?  Or when I rebased it disappeared.def 

```
test_diff_models_with_related_fields(self):                             
          """No error is raised when comparing models with related fields."""     
          first = RelatedModel()                                                  
          second = RelatedModel()                                                 
          model_instance_diff(first, second)     


```

Pushing again ... I don't have postgres locally to test against, so I need to use your cicd for testing.

**Comment by rrauenza** [comment]
I think I'm narrowing this down. 

The model_instance_diff is passed with null, instance during a fixture load:

```
Based on this stack trace when loading fixtures:                      
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/core/management/commands/loaddata.py line 114 in loaddata
          # self.load_label(fixture_label)                                        
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/core/management/commands/loaddata.py line 181 in load_label
          # obj.save(using=self.using)                                            
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/core/serializers/base.py line 223 in save
          # models.Model.save_base(self.object, using=using, raw=True, **kwargs)  
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/db/models/base.py line 790 in save_base
          # update_fields=update_fields, raw=raw, using=using,                    
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/dispatch/dispatcher.py line 175 in send
          # for receiver in self._live_receivers(sender)                          
          # virtualenv-3.6.8/lib/python3.6/site-packages/django/dispatch/dispatcher.py line 175 in <listcomp>
          # for receiver in self._live_receivers(sender)                          
          # virtualenv-3.6.8/lib/python3.6/site-packages/auditlog/receivers.py line 16 in log_create
          # changes = model_instance_diff(None, instance) <------- HERE           
          # virtualenv-3.6.8/lib/python3.6/site-packages/auditlog/diff.py line 135 in model_instance_diff
          # new_value = get_field_value(new, field)                               
          # virtualenv-3.6.8/lib/python3.6/site-packages/auditlog/diff.py line 80 in get_field_value
          # value = field.default if field.default is not NOT_PROVIDED else None  
          # AttributeError: Problem installing fixture 'data.json': 'OneToOneRel' object has no attribute 'default'
```

For this to happen, though, we must trigger an ObjectDoesNotExist.

(code from before my change:)
```
try:                                                                        
          if isinstance(field, DateTimeField):                                    
              # DateTimeFields are timezone-aware, so we need to convert the field
              # to its naive form before we can accurately compare them for changes.
              value = field.to_python(getattr(obj, field.name, None))             
              if value is not None and settings.USE_TZ and not timezone.is_naive(value):
                  value = timezone.make_naive(value, timezone=timezone.utc)       
          elif isinstance(field, JSONField):                                      
              value = field.to_python(getattr(obj, field.name, None))             
          else:                                                                   
              value = smart_str(getattr(obj, field.name, None))                   
      except ObjectDoesNotExist:                                                  
          value = field.default if field.default is not NOT_PROVIDED else None    
```

I'm not sure how to trigger this.  I've seen it when model.foo is a FK that points to None.  Oh.. I think its triggered from the reverse lookup from the fk model. 

Trying more tests...

**Comment by rrauenza** [comment]
FYI, still pushing tests -- we actually want them to fail as I'm trying to test that we catch the failure case -- fix is disabled currently.

**Comment by hramezani** [comment]
I think it's better to run the tests locally. Because running them on CI takes time

**Comment by rrauenza** [comment]
@hramezani I think I have figured out what is going on now.

I think since my proposed change long ago, I think the code now filters what fields go through the diff generator.  In the past, the reverse related field got captured.  Which actually doesn't make sense to do anyway.  So I suspect somewhere we only grab "local" fields to the object.  So the code is never going to trigger because the one to one related field type never gets to the diff function.

What I'd like to do is add a unit test for this, without the fix.

**Comment by rrauenza** [comment]
In fact, it looks like this is where we avoid remote fields::

```
def track_field(field):                                                         
      """                                                                         
      Returns whether the given field should be tracked by Auditlog.              
                                                                                  
      Untracked fields are many-to-many relations and relations to the Auditlog LogEntry model.
                                                                                  
      :param field: The field to check.                                           
      :type field: Field                                                          
      :return: Whether the given field should be tracked.                         
      :rtype: bool                                                                
      """                                                                         
      from auditlog.models import LogEntry                                        
                                                                                  
      # Do not track many to many relations                                       
      if field.many_to_many:                                                      
          return False                                                            
                                                                                  
      # Do not track relations to LogEntry                                        
      if (                                                                        
          getattr(field, "remote_field", None) is not None                        
          and field.remote_field.model == LogEntry                                
      ):                                                                          
          return False                                                            
                                                                                  
      return True              
```

**Review by hramezani — APPROVED** [review]
Thanks @rrauenza for your effort :+1:

**Pull request merged**
