### PR TITLE
Replace ugettext with gettext for django4 compatibility

### LINKED ISSUE #334: RemovedInDjango40Warning: ugettext deprecated in django 3 and removed in django 4
From first tests with Django 4.0 we seem to be "blocked" to upgrade Django versions by django-auditlog, as the pre-release version still uses at least in `auditlog/models.py` an import of `ugettext_lazy` which was deprecated in Django 3 and removed in Django 4.

This should be a pretty simple fix to "just' replace `ugettext_lazy` with `gettext_lazy`, hoping now other issues come up.

Versions:
- django 4.0
- django-auditlog 1.0a1.

### PR DESCRIPTION
**Pull request by wearebasti**
This should be a "in-place-replacement" with hopefully no side effects, would be great to have it in the pre-release package, for example as 1.0a2 :) 

This should fix #334

### CODE REVIEW

**Comment by hramezani** [comment]
This module uses [django-jsonfield](https://github.com/adamchainz/django-jsonfield) which has to be removed because Django internally has a `JsonField`. 
It seems `djagno-jsonfield` uses `ugettext_lazy` that does not exist in Django anymore:

```
      from jsonfield.fields import JSONField
    File "/home/runner/work/django-auditlog/django-auditlog/.tox/py39-django32/lib/python3.9/site-packages/jsonfield/__init__.py", line 3, in <module>
      from .fields import JSONField
    File "/home/runner/work/django-auditlog/django-auditlog/.tox/py39-django32/lib/python3.9/site-packages/jsonfield/fields.py", line 9, in <module>
      from django.utils.translation import ugettext_lazy as _
  ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (/home/runner/work/django-auditlog/django-auditlog/.tox/py39-django32/lib/python3.9/site-packages/django/utils/translation/__init__.py)```

**Review by Linkid — APPROVED** [review]

**Comment by Linkid** [comment]
I think this PR should be merged anyway because this is the only case in the codebase. The `django-jsonfield` dependency is another subject that should be fixed in another PR. What do you think @hramezani ?

**Comment by hramezani** [comment]
@Linkid as far as the CI is not green, I would prefer to don't merge the PR

**Comment by Linkid** [comment]
@hramezani Well, the CI will be green until we add Django 4.0 to tox.
If you're talking about checks in this PR, is it not green due to a bug I fixed in #338 (the django version is not the expected one ;)).

**Comment by hramezani** [comment]
@Linkid yes. so we need a rebase on this patch.

**Review by Linkid — CHANGES_REQUESTED** [review]
You can rebase your code to make tests pass ;)

**Comment by hramezani** [comment]
Let's wait for @Linkid pr https://github.com/jazzband/django-auditlog/pull/339 and then the CI will be green.

**Comment by Linkid** [comment]
> Let's wait for @Linkid pr #339 and then the CI will be green.

There is no test on django4 (yet), so the CI will be green only after a rebase thanks to #338 ;).

**Comment by hramezani** [comment]
Ah ok. let's merge then. this one is simple ;)

**Comment by hramezani** [comment]
Superseded in https://github.com/jazzband/django-auditlog/pull/340

**Pull request closed without merging**
