### PR TITLE
make field value retrieval slightly more robust

### LINKED ISSUE #169: one to one relation error
one to one relation error happening on diff.py line 80 where field object does not have attribute default if onetoonerel type field. suggested patch
            if hasattr(field, 'default'):
                value = field.default if field.default is not NOT_PROVIDED else None
            else:
                value = None

### PR DESCRIPTION
**Pull request by euven**
when no field 'default' attribute is present

credit to: https://github.com/stherrien

Fixes #169

### CODE REVIEW

**Comment by mavericm1** [comment]
I can confirm that this issue still exists in master.   forking and making this single line change has fixed the default onetoonerel error.   If you'd like i can submit a new PR against current master.   credit goes to bynare.    https://github.com/mavericm1/django-auditlog

**Comment by Linkid** [comment]
Hi @bynare. Thanks for your PR.
Could you please rebase ? Thanks.

**Comment by hairypalm** [comment]
Hi there -- issue remains and I confirm that @euven one line change PR resolves.  Without it I cannot loaddata as OneToOneField does not have a **default** attribute.  Please advise whether I should maintain a local fork or if this PR from will be merged soon.  Thank you!

**Comment by hramezani** [comment]
Hi @hairypalm. Thanks for confirming that fix.

@euven Could you please:

- Rebase your patch
- Add a regression test
- Add a change log entry to https://github.com/jazzband/django-auditlog/blob/master/CHANGELOG.md

@hairypalm it would be great if you could add a test function or code that helps us to add a test for it.

**Comment by hramezani** [comment]
Added in https://github.com/jazzband/django-auditlog/commit/a56d0e6f784f3d0e1107f41c8c7a3f2423686c14

**Pull request closed without merging**
